name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore --runtime win10-x64
    - name: Build
      run: dotnet build .\DbAssertions.Test\DbAssertions.Test.csproj --runtime win10-x64 --no-restore
    - name: Test
      run: dotnet test --runtime win10-x64 --no-build --verbosity normal
